name: Sync with Upstream and Build

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: feature/native-scale-support
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ersatztv/ersatztv.git || true
          git fetch upstream

      - name: Check for upstream changes
        id: check_changes
        run: |
          git fetch upstream main
          BEHIND=$(git rev-list --count HEAD..upstream/main)
          echo "behind=$BEHIND" >> $GITHUB_OUTPUT
          echo "Commits behind upstream: $BEHIND"

      - name: Merge upstream changes
        if: steps.check_changes.outputs.behind > 0
        run: |
          echo "Merging upstream/main into feature/native-scale-support"
          git merge upstream/main --no-edit || {
            echo "Merge conflict detected!"
            echo "::warning::Manual intervention required - merge conflicts with upstream"
            exit 1
          }

      - name: Push merged changes
        if: steps.check_changes.outputs.behind > 0
        run: |
          git push origin feature/native-scale-support

      - name: Set up Docker Buildx
        if: steps.check_changes.outputs.behind > 0
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.check_changes.outputs.behind > 0
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check_changes.outputs.behind > 0
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ersatztv:scale-support
            ghcr.io/${{ github.repository_owner }}/ersatztv:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        if: steps.check_changes.outputs.behind > 0
        run: |
          echo "✅ Successfully synced with upstream and rebuilt Docker image" >> $GITHUB_STEP_SUMMARY
          echo "📦 Image: ghcr.io/${{ github.repository_owner }}/ersatztv:scale-support" >> $GITHUB_STEP_SUMMARY

      - name: No changes
        if: steps.check_changes.outputs.behind == 0
        run: |
          echo "✅ Already up to date with upstream" >> $GITHUB_STEP_SUMMARY
